import type { Metadata } from "next";


import "./globals.css";

import StatSig from "@/components/StatSig/StatSig";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StatSig>
        <body>
          {children}
        </body>
      </StatSig>
    </html>
  );
}
